### PR TITLE
Fixes a number of Pointer related issues

### LINKED ISSUE #748: SceneContext does not export the pointer instance
As it does with 'mouse'.

### PR DESCRIPTION
**Pull request by hobnob**
Addresses the following issues:
* Adds `pointers` to `SceneContext` (#748)
* Add new methods to `Pointers` ( #749)
* Changes the way events are captured for pointers ( #692)
* Adds a new `PointerEvent.PointerClick` method, which is fired when a `PointerDown` event is followed by a `PointerUp` event for the same button within a specified, configurable, time frame (defaults to 200ms) (#703)
* Updates UI to use `Pointer` rather than `Mouse` (#747)

### CODE REVIEW

File: indigo/indigo/src/main/scala/indigo/platform/events/WorldEvents.scala [hunk 1]
```diff
@@ -23,6 +23,11 @@ import org.scalajs.dom.document
 import org.scalajs.dom.html
 import org.scalajs.dom.window
 
+import scala.scalajs.js.Date
+
+@SuppressWarnings(Array("scalafix:DisableSyntax.var"))
+var pointerButtons: Map[Double, Batch[(Int, Date)]] = Map.empty
```
Comment (davesmith00000) [inline indigo/indigo/src/main/scala/indigo/platform/events/WorldEvents.scala:29]: This can't be here as a top level this, needs to move inside the class at the very least, i.e.:

```scala
final class WorldEvents:
  @SuppressWarnings(Array("scalafix:DisableSyntax.var"))
  var pointerButtons: Map[Double, Batch[(Int, Date)]] = Map.empty
```

Comment (davesmith00000) [reply indigo/indigo/src/main/scala/indigo/platform/events/WorldEvents.scala:29]: And it should probably be `private`.

**Review by davesmith00000 — COMMENTED** [review]
This looks good. One big no-no jumped out at me, will check it over again with fresh eyes.

File: indigo/indigo/src/main/scala/indigo/platform/events/WorldEvents.scala (hunk 1 above)
Comment (hobnob) [reply indigo/indigo/src/main/scala/indigo/platform/events/WorldEvents.scala:29]: All done
